DROP TABLE RATING;
DROP table ORDER_TBL ;
DROP TABLE SUPPLIER_PRICING;
DROP table PRODUCT ;
use ecommerce;
show tables;
create table supplier (
SUPP_ID INT ,
SUPP_NAME VARCHAR(50) NOT NULL,
SUPP_CITY VARCHAR(50) NOT NULL,
SUPP_PHONE VARCHAR(50) NOT NULL,
PRIMARY KEY(SUPP_ID) 
);

create table customer (
CUS_ID INT ,
CUS_NAME VARCHAR(20) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY VARCHAR(30) NOT NULL,
CUS_GENDER CHAR,
PRIMARY KEY(CUS_ID) 
);

create table category (
CAT_ID INT ,
CAT_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (CAT_ID)
);

CREATE table PRODUCT (
PRO_ID INT ,
PRO_NAME VARCHAR(20),
PRO_DESC	VARCHAR(60),
CAT_ID	INT,
PRIMARY KEY (PRO_ID),
FOREIGN KEY(CAT_ID) REFERENCES CATEGORY(CAT_ID)
);

CREATE TABLE SUPPLIER_PRICING(
PRICING_ID	INT,
PRO_ID	INT,
SUPP_ID	INT,
SUPP_PRICE	INT DEFAULT 0,
PRIMARY KEY (PRICING_ID),
FOREIGN KEY(PRO_ID) REFERENCES  PRODUCT(PRO_ID),
FOREIGN KEY(SUPP_ID) REFERENCES  supplier(SUPP_ID)
);

CREATE TABLE order_tbl (
ORD_ID	INT,
ORD_AMOUNT	INT NOT NULL,
ORD_DATE	DATE NOT NULL,
CUS_ID	INT,
PRICING_ID	INT ,
PRIMARY KEY (ORD_ID),
FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID),
FOREIGN KEY (PRICING_ID) REFERENCES SUPPLIER_PRICING(PRICING_ID)
);

CREATE TABLE rating (
RAT_ID	INT, 
ORD_ID	INT ,
RAT_RATSTARS	INT NOT NULL,
PRIMARY KEY(RAT_ID),
FOREIGN KEY (ORD_ID) REFERENCES order_tbl(ORD_ID)
);